### PR TITLE
:sparkles: Add archive policy for games

### LINKED ISSUE #150: :bug: Error tips always hang on
**Situation 1:** The error tip cannot be removed if once triggered, can it would cover the content behind.

Image

**Situation 2:** Error incorrectly valiadted after creating hints.

Image

### LINKED ISSUE #151: :sparkles: show writeup after challenge is archived

### LINKED ISSUE #153: :bug: Cannot load unlocked tips if refresh at hint page directly
Image

Image

actually unlocked.

Directly refresh at this page, for exmaple, `/games/1/challenges?challenge=34&tab=hints` to reproduct.

### PR DESCRIPTION
**Pull request by Cnily03**
What this PR does:

- Resolves #151 
- Fixes #150 
- Fixes #153

This PR also beautified the input outline style with icon:

image

### CODE REVIEW

File: web/src/lib/blocks/challenge/index.tsx [hunk 1]
```diff
@@ -283,6 +285,10 @@ export default function (props: {
         endPanel={() => (
           <BottomPanel
             inGame={props.inGame ?? false}
+            archived={
+              props.archived ??
+              (props.inGame ? !((challengeStore.current?.archive_at?.toMillis() || 0) > Date.now()) : true)
```
Comment (Cnily03) [inline web/src/lib/blocks/challenge/index.tsx]: Default value:
- if in game, auto detect whether the challenge is archived. if not set, treat it as open
- if not in game (the game is archived), treat the challenge as archived

File: crates/migrator/src/migrations/m_20250226_000001_archive_policy.rs [hunk 2]
```diff
@@ -0,0 +1,42 @@
+use sea_orm_migration::prelude::*;
+
+use super::m_20240104_000001_create_game::Game;
+pub struct Migration;
+
+impl MigrationName for Migration {
+  fn name(&self) -> &str {
+    "m_20250226_000001_archive_policy"
```
Comment (Reverier-Xu) [inline crates/migrator/src/migrations/m_20250226_000001_archive_policy.rs]:
```suggestion
    "m_20250226_000001_game_archive_policy"
```

please also change the file name too.

**Review by Reverier-Xu — CHANGES_REQUESTED** [review]

File: crates/migrator/src/migrations/mod.rs [hunk 3]
```diff
@@ -26,3 +26,4 @@ pub mod m_20241220_000001_game_award_rates;
 pub mod m_20241226_000001_game_traffic;
 pub mod m_20250105_000001_create_oauth_provider;
 pub mod m_20250114_000001_create_oauth_index;
+pub mod m_20250226_000001_archive_policy;
```
Comment (Cnily03) [inline crates/migrator/src/migrations/mod.rs]:
```suggestion
pub mod m_20250226_000001_game_archive_policy;
```

File: crates/migrator/src/lib.rs [hunk 4]
```diff
@@ -40,6 +40,7 @@ impl MigratorTrait for Migrator {
       Box::new(migrations::m_20241226_000001_game_traffic::Migration),
       Box::new(migrations::m_20250105_000001_create_oauth_provider::Migration),
       Box::new(migrations::m_20250114_000001_create_oauth_index::Migration),
+      Box::new(migrations::m_20250226_000001_archive_policy::Migration),
```
Comment (Cnily03) [inline crates/migrator/src/lib.rs]:
```suggestion
      Box::new(migrations::m_20250226_000001_game_archive_policy::Migration),
```

**Review by Cnily03 — COMMENTED** [review]
And please rename `m_20250226_000001_archive_policy.rs` to `m_20250226_000001_game_archive_policy`.

File: web/src/lib/blocks/challenge/hints.tsx [hunk 5]
```diff
@@ -95,6 +96,11 @@ export default function (_props: {
         refreshHint();
       });
     }
+    if (gameStore.current && gameStore.team) {
+      untrack(() => {
+        refreshHint();
+      });
+    }
```
Comment (Cnily03) [inline web/src/lib/blocks/challenge/hints.tsx:108]: Fixes #153

File: web/src/lib/widgets/input.tsx [hunk 6]
```diff
@@ -47,12 +61,18 @@ export default function (props: TextInputProps & ComponentProps<"input">) {
...
+              (others.type === "password" || inputProps.extraBtn) && "!rounded-r-none"
             )}
             type={type()}
+            on:blur={() => {
+              lastError = error();
+              setError();
+            }}
+            on:focus={() => {
+              setError(lastError);
+            }}
```
Comment (Reverier-Xu) [inline web/src/lib/widgets/input.tsx]: Maybe you should setup a boolean signal to store the input focus state, then you can only use `props.error` to implement the same effect, and drop `error` signal and `lastError`, which store a simple error message in same for three times.

**Review by Reverier-Xu — CHANGES_REQUESTED** [review]
We have a nightly-only rustfmt config in the `rustfmt.toml`, please run:

```
cargo +nightly fmt
```

before the next commit.

Besides `cargo fmt` and input state handling, No other changes need to be made, thanks!

**Review by Cnily03 — COMMENTED** [review]
Created a commit that would re-cache the valid token if not in the cache, in order to avoid user logging out but with valid token.

File: crates/server/src/middleware/auth.rs [hunk 7]
```diff
@@ -149,6 +146,23 @@ pub async fn extract_user_info(
...
+        error!("failed to store token: {:?}", err);
+      })
+      .ok();
+    cache
+      .at("token")
+      .push(format!("user-{}", token.id), token_str)
+      .await
+      .ok();
+  }
+
```
Comment (Cnily03) [inline crates/server/src/middleware/auth.rs]: When token is valid but does not exist in the cache. The current version would return default token, which let the user logged out and mus re-login.

This code snippet is a patch that re-cache the missing valid token. And it also avoid all user logging out after `flushall` event caused by migrations.

Theo only thing I as worried about is there would be a lot of `decode_token` call when many users are online and make requests after migrations. Does the server could hold on?

Do you have any suggestions? @Reverier-Xu My motivation is to flush some cache but avoid user logging out after migrations.

**Comment by Cnily03** [comment]
**TODO:** add block conditions in `unlock_hint` if game or challenges are archived.

File: crates/server/src/middleware/auth.rs (hunk 7 above)
Comment (Reverier-Xu) [reply crates/server/src/middleware/auth.rs]: No, we **should** cleanup all old states after version bumping with breaking changes.

**Review by Reverier-Xu — APPROVED** [review]
thanks!

**Comment by Cnily03** [comment]
**TODO:** if the user update its own user config, resign token.

**Review by Reverier-Xu — APPROVED** [review]
